export const STARTUPS = [
  {
    id: "nova-health",
    name: "NovaHealth AI",
    sector: "HealthTech",
    stage: "Series A",
    logo: "NH",
    color: "from-emerald-400 to-teal-600",
    description: "AI-driven diagnostics platform reducing misdiagnosis rates by 40% across rural hospitals.",
    expectedIRR: 0.42,
    pd12m: 0.08,
    fragilityScore: 18,
    revenueConcentration: 24,
    arrGrowth: 187,
    runway: 22,
    stressTest: {
      base:   { irr: 0.42, pd: 0.08 },
      stress: { irr: 0.28, pd: 0.18 },
      severe: { irr: 0.10, pd: 0.38 },
    },
    tags: ["AI", "Healthcare", "B2B SaaS"],
    contact: {
      name: "Dr. Aisha Patel",
      role: "CEO & Co-Founder",
      email: "aisha@novahealth.ai",
      linkedin: "https://linkedin.com/in/aishapatel",
      website: "https://novahealth.ai",
      location: "San Francisco, CA",
      phone: "+1 (415) 823-4401",
    },
  },
  {
    id: "carbon-ledger",
    name: "CarbonLedger",
    sector: "ClimaTech",
    stage: "Seed",
    logo: "CL",
    color: "from-green-400 to-lime-600",
    description: "Blockchain-based carbon credit marketplace connecting enterprises with verified offset projects.",
    expectedIRR: 0.55,
    pd12m: 0.14,
    fragilityScore: 34,
    revenueConcentration: 61,
    arrGrowth: 310,
    runway: 14,
    stressTest: {
      base:   { irr: 0.55, pd: 0.14 },
      stress: { irr: 0.31, pd: 0.29 },
      severe: { irr: -0.05, pd: 0.52 },
    },
    tags: ["Climate", "Web3", "Marketplace"],
    contact: {
      name: "James Osei",
      role: "Founder & CTO",
      email: "james@carbonledger.io",
      linkedin: "https://linkedin.com/in/jamesosei",
      website: "https://carbonledger.io",
      location: "London, UK",
      phone: "+44 20 7946 0123",
    },
  },
  {
    id: "fleet-forge",
    name: "FleetForge",
    sector: "Logistics",
    stage: "Series B",
    logo: "FF",
    color: "from-blue-400 to-indigo-600",
    description: "Autonomous fleet management SaaS cutting last-mile delivery costs by 32% for mid-market retailers.",
    expectedIRR: 0.31,
    pd12m: 0.05,
    fragilityScore: 12,
    revenueConcentration: 18,
    arrGrowth: 94,
    runway: 36,
    stressTest: {
      base:   { irr: 0.31, pd: 0.05 },
      stress: { irr: 0.22, pd: 0.11 },
      severe: { irr: 0.14, pd: 0.22 },
    },
    tags: ["Logistics", "SaaS", "Automation"],
    contact: {
      name: "Maria Kovacs",
      role: "CEO",
      email: "maria@fleetforge.com",
      linkedin: "https://linkedin.com/in/mariakovacs",
      website: "https://fleetforge.com",
      location: "Berlin, Germany",
      phone: "+49 30 5678 9012",
    },
  },
  {
    id: "qubit-finance",
    name: "QubitFinance",
    sector: "FinTech",
    stage: "Series A",
    logo: "QF",
    color: "from-purple-400 to-violet-600",
    description: "Quantum-computing-enhanced portfolio optimization for family offices and RIAs.",
    expectedIRR: 0.48,
    pd12m: 0.11,
    fragilityScore: 26,
    revenueConcentration: 42,
    arrGrowth: 145,
    runway: 19,
    stressTest: {
      base:   { irr: 0.48, pd: 0.11 },
      stress: { irr: 0.30, pd: 0.24 },
      severe: { irr: 0.08, pd: 0.45 },
    },
    tags: ["FinTech", "Quantum", "B2B"],
    contact: {
      name: "Dr. Lena Strauss",
      role: "Co-Founder & COO",
      email: "lena@qubitfinance.com",
      linkedin: "https://linkedin.com/in/lenastrauss",
      website: "https://qubitfinance.com",
      location: "New York, NY",
      phone: "+1 (212) 555-0198",
    },
  },
  {
    id: "pulse-grid",
    name: "PulseGrid",
    sector: "Energy",
    stage: "Seed",
    logo: "PG",
    color: "from-orange-400 to-rose-500",
    description: "Distributed energy storage network enabling peer-to-peer electricity trading in underserved markets.",
    expectedIRR: 0.63,
    pd12m: 0.21,
    fragilityScore: 47,
    revenueConcentration: 55,
    arrGrowth: 420,
    runway: 11,
    stressTest: {
      base:   { irr: 0.63, pd: 0.21 },
      stress: { irr: 0.38, pd: 0.40 },
      severe: { irr: -0.10, pd: 0.65 },
    },
    tags: ["Energy", "P2P", "Hardware"],
    contact: {
      name: "Tariq Al-Rashid",
      role: "Founder & CEO",
      email: "tariq@pulsegrid.energy",
      linkedin: "https://linkedin.com/in/tariqalrashid",
      website: "https://pulsegrid.energy",
      location: "Dubai, UAE",
      phone: "+971 4 123 4567",
    },
  },
  {
    id: "synthex-bio",
    name: "SynthexBio",
    sector: "BioTech",
    stage: "Series A",
    logo: "SB",
    color: "from-pink-400 to-fuchsia-600",
    description: "AI-accelerated protein synthesis platform cutting drug discovery timelines from 5 years to 18 months.",
    expectedIRR: 0.51,
    pd12m: 0.13,
    fragilityScore: 29,
    revenueConcentration: 38,
    arrGrowth: 210,
    runway: 20,
    stressTest: {
      base:   { irr: 0.51, pd: 0.13 },
      stress: { irr: 0.32, pd: 0.27 },
      severe: { irr: 0.09, pd: 0.48 },
    },
    tags: ["BioTech", "AI", "Drug Discovery"],
    contact: {
      name: "Dr. Sofia Reyes",
      role: "CEO & Co-Founder",
      email: "sofia@synthexbio.com",
      linkedin: "https://linkedin.com/in/sofiareyes",
      website: "https://synthexbio.com",
      location: "Boston, MA",
      phone: "+1 (617) 334-8821",
    },
  },
  {
    id: "gridlens",
    name: "GridLens",
    sector: "PropTech",
    stage: "Series B",
    logo: "GL",
    color: "from-yellow-400 to-orange-500",
    description: "Computer-vision platform for real-time building energy audits, deployed across 3,000+ commercial properties.",
    expectedIRR: 0.29,
    pd12m: 0.06,
    fragilityScore: 15,
    revenueConcentration: 22,
    arrGrowth: 88,
    runway: 30,
    stressTest: {
      base:   { irr: 0.29, pd: 0.06 },
      stress: { irr: 0.19, pd: 0.14 },
      severe: { irr: 0.11, pd: 0.25 },
    },
    tags: ["PropTech", "Computer Vision", "SaaS"],
    contact: {
      name: "Ben Hartley",
      role: "CTO & Founder",
      email: "ben@gridlens.io",
      linkedin: "https://linkedin.com/in/benhartley",
      website: "https://gridlens.io",
      location: "Chicago, IL",
      phone: "+1 (312) 409-7755",
    },
  },
  {
    id: "agro-pulse",
    name: "AgroPulse",
    sector: "AgriTech",
    stage: "Series A",
    logo: "AP",
    color: "from-lime-400 to-green-600",
    description: "IoT soil-intelligence network helping smallholder farmers boost yields by 35% while cutting water usage by half.",
    expectedIRR: 0.44,
    pd12m: 0.10,
    fragilityScore: 22,
    revenueConcentration: 31,
    arrGrowth: 160,
    runway: 18,
    stressTest: {
      base:   { irr: 0.44, pd: 0.10 },
      stress: { irr: 0.27, pd: 0.22 },
      severe: { irr: 0.07, pd: 0.41 },
    },
    tags: ["AgriTech", "IoT", "Sustainability"],
    contact: {
      name: "Priya Nambiar",
      role: "Founder & CEO",
      email: "priya@agropulse.ag",
      linkedin: "https://linkedin.com/in/priyanambiar",
      website: "https://agropulse.ag",
      location: "Bangalore, India",
      phone: "+91 80 4567 8901",
    },
  },
  {
    id: "nexum-legal",
    name: "NexumLegal",
    sector: "LegalTech",
    stage: "Seed",
    logo: "NL",
    color: "from-slate-400 to-gray-600",
    description: "LLM-powered contract review and clause negotiation tool reducing in-house legal costs by 60% for mid-market firms.",
    expectedIRR: 0.58,
    pd12m: 0.17,
    fragilityScore: 38,
    revenueConcentration: 49,
    arrGrowth: 290,
    runway: 13,
    stressTest: {
      base:   { irr: 0.58, pd: 0.17 },
      stress: { irr: 0.33, pd: 0.34 },
      severe: { irr: 0.02, pd: 0.55 },
    },
    tags: ["LegalTech", "LLM", "B2B SaaS"],
    contact: {
      name: "Natasha Volkov",
      role: "CEO",
      email: "natasha@nexumlegal.com",
      linkedin: "https://linkedin.com/in/tashavolkov",
      website: "https://nexumlegal.com",
      location: "Toronto, Canada",
      phone: "+1 (416) 882-3340",
    },
  },
  {
    id: "deeproute",
    name: "DeepRoute",
    sector: "Autonomous Vehicles",
    stage: "Series B",
    logo: "DR",
    color: "from-sky-400 to-cyan-600",
    description: "Level-4 autonomous trucking middleware enabling freight carriers to retrofit existing fleets at 1/10th the cost of full replacement.",
    expectedIRR: 0.36,
    pd12m: 0.07,
    fragilityScore: 20,
    revenueConcentration: 28,
    arrGrowth: 112,
    runway: 28,
    stressTest: {
      base:   { irr: 0.36, pd: 0.07 },
      stress: { irr: 0.24, pd: 0.15 },
      severe: { irr: 0.12, pd: 0.28 },
    },
    tags: ["Autonomous", "Logistics", "Deep Tech"],
    contact: {
      name: "Leon Bauer",
      role: "Co-Founder & CTO",
      email: "leon@deeproute.ai",
      linkedin: "https://linkedin.com/in/leonbauer",
      website: "https://deeproute.ai",
      location: "Munich, Germany",
      phone: "+49 89 2345 6789",
    },
  },
  {
    id: "credify",
    name: "Credify",
    sector: "FinTech",
    stage: "Seed",
    logo: "CR",
    color: "from-violet-400 to-purple-700",
    description: "Alternative credit scoring engine using 400+ behavioural signals to serve the 1.4 billion credit-invisible population.",
    expectedIRR: 0.67,
    pd12m: 0.22,
    fragilityScore: 50,
    revenueConcentration: 58,
    arrGrowth: 480,
    runway: 10,
    stressTest: {
      base:   { irr: 0.67, pd: 0.22 },
      stress: { irr: 0.40, pd: 0.42 },
      severe: { irr: -0.08, pd: 0.67 },
    },
    tags: ["FinTech", "Credit", "Emerging Markets"],
    contact: {
      name: "Amara Diallo",
      role: "Founder & CEO",
      email: "amara@credify.finance",
      linkedin: "https://linkedin.com/in/amaradiallo",
      website: "https://credify.finance",
      location: "Lagos, Nigeria",
      phone: "+234 1 234 5678",
    },
  },
  {
    id: "axon-robotics",
    name: "AxonRobotics",
    sector: "Robotics",
    stage: "Series A",
    logo: "AR",
    color: "from-red-400 to-rose-700",
    description: "Soft-robotics end-effectors enabling general-purpose picking and packing robots to handle irregular SKUs with 99.2% accuracy.",
    expectedIRR: 0.46,
    pd12m: 0.12,
    fragilityScore: 27,
    revenueConcentration: 35,
    arrGrowth: 175,
    runway: 17,
    stressTest: {
      base:   { irr: 0.46, pd: 0.12 },
      stress: { irr: 0.29, pd: 0.25 },
      severe: { irr: 0.08, pd: 0.44 },
    },
    tags: ["Robotics", "Hardware", "Manufacturing"],
    contact: {
      name: "Kenji Mori",
      role: "CTO & Co-Founder",
      email: "kenji@axonrobotics.jp",
      linkedin: "https://linkedin.com/in/kenjimori",
      website: "https://axonrobotics.jp",
      location: "Tokyo, Japan",
      phone: "+81 3 1234 5678",
    },
  },
  {
    id: "aeroledge",
    name: "AeroLedge",
    sector: "SpaceTech",
    stage: "Seed",
    logo: "AL",
    color: "from-indigo-400 to-blue-800",
    description: "Low-orbit satellite edge-computing nodes offering sub-20ms latency cloud processing for maritime and aviation clients.",
    expectedIRR: 0.72,
    pd12m: 0.26,
    fragilityScore: 55,
    revenueConcentration: 62,
    arrGrowth: 560,
    runway: 9,
    stressTest: {
      base:   { irr: 0.72, pd: 0.26 },
      stress: { irr: 0.42, pd: 0.47 },
      severe: { irr: -0.15, pd: 0.71 },
    },
    tags: ["SpaceTech", "Edge Computing", "Deep Tech"],
    contact: {
      name: "Elena Vasiliev",
      role: "CEO & Founder",
      email: "elena@aeroledge.space",
      linkedin: "https://linkedin.com/in/elenavasiliev",
      website: "https://aeroledge.space",
      location: "Luxembourg",
      phone: "+352 20 123 456",
    },
  },
  {
    id: "mentalytics",
    name: "Mentalytics",
    sector: "HealthTech",
    stage: "Series A",
    logo: "MN",
    color: "from-teal-400 to-cyan-700",
    description: "Wearable-integrated mental health platform delivering real-time mood analytics and personalised CBT micro-interventions.",
    expectedIRR: 0.38,
    pd12m: 0.09,
    fragilityScore: 21,
    revenueConcentration: 26,
    arrGrowth: 140,
    runway: 21,
    stressTest: {
      base:   { irr: 0.38, pd: 0.09 },
      stress: { irr: 0.24, pd: 0.20 },
      severe: { irr: 0.08, pd: 0.38 },
    },
    tags: ["HealthTech", "Wearables", "Mental Health"],
    contact: {
      name: "Dr. Yuki Tanaka",
      role: "CEO",
      email: "yuki@mentalytics.io",
      linkedin: "https://linkedin.com/in/yukitanaka",
      website: "https://mentalytics.io",
      location: "Singapore",
      phone: "+65 6123 4567",
    },
  },
  {
    id: "payvault",
    name: "PayVault",
    sector: "FinTech",
    stage: "Series B",
    logo: "PV",
    color: "from-emerald-500 to-green-800",
    description: "Embedded payroll-on-demand infrastructure for gig economy platforms, processing $2.1B in annual disbursements.",
    expectedIRR: 0.27,
    pd12m: 0.04,
    fragilityScore: 10,
    revenueConcentration: 15,
    arrGrowth: 75,
    runway: 40,
    stressTest: {
      base:   { irr: 0.27, pd: 0.04 },
      stress: { irr: 0.18, pd: 0.10 },
      severe: { irr: 0.10, pd: 0.20 },
    },
    tags: ["FinTech", "Embedded Finance", "Gig Economy"],
    contact: {
      name: "Carlos Mendez",
      role: "CEO",
      email: "carlos@payvault.com",
      linkedin: "https://linkedin.com/in/carlosmendez",
      website: "https://payvault.com",
      location: "Mexico City, Mexico",
      phone: "+52 55 1234 5678",
    },
  },
  {
    id: "neuro-chip",
    name: "NeuroChip",
    sector: "Semiconductor",
    stage: "Series A",
    logo: "NC",
    color: "from-amber-400 to-yellow-700",
    description: "Neuromorphic inference chip delivering 40× better energy-efficiency than GPU for on-device AI workloads.",
    expectedIRR: 0.53,
    pd12m: 0.14,
    fragilityScore: 32,
    revenueConcentration: 44,
    arrGrowth: 230,
    runway: 16,
    stressTest: {
      base:   { irr: 0.53, pd: 0.14 },
      stress: { irr: 0.31, pd: 0.29 },
      severe: { irr: 0.06, pd: 0.50 },
    },
    tags: ["Semiconductor", "AI Hardware", "Deep Tech"],
    contact: {
      name: "Dr. Wei Zhang",
      role: "Founder & CTO",
      email: "wei@neurochip.ai",
      linkedin: "https://linkedin.com/in/weizhang",
      website: "https://neurochip.ai",
      location: "Shenzhen, China",
      phone: "+86 755 1234 5678",
    },
  },
  {
    id: "safechain",
    name: "SafeChain",
    sector: "CyberSecurity",
    stage: "Series B",
    logo: "SC",
    color: "from-cyan-600 to-blue-900",
    description: "Zero-trust supply-chain security platform providing real-time SBOM monitoring for Fortune 500 enterprises.",
    expectedIRR: 0.33,
    pd12m: 0.05,
    fragilityScore: 14,
    revenueConcentration: 20,
    arrGrowth: 98,
    runway: 33,
    stressTest: {
      base:   { irr: 0.33, pd: 0.05 },
      stress: { irr: 0.22, pd: 0.12 },
      severe: { irr: 0.13, pd: 0.24 },
    },
    tags: ["CyberSecurity", "Zero-Trust", "Enterprise"],
    contact: {
      name: "Isabelle Moreau",
      role: "CEO",
      email: "isabelle@safechain.io",
      linkedin: "https://linkedin.com/in/isabellemoreau",
      website: "https://safechain.io",
      location: "Paris, France",
      phone: "+33 1 2345 6789",
    },
  },
  {
    id: "edusync",
    name: "EduSync",
    sector: "EdTech",
    stage: "Seed",
    logo: "ES",
    color: "from-rose-400 to-pink-700",
    description: "Adaptive learning OS for K-12 schools that personalises curricula in real time, improving test scores by 28% on average.",
    expectedIRR: 0.49,
    pd12m: 0.15,
    fragilityScore: 36,
    revenueConcentration: 47,
    arrGrowth: 265,
    runway: 12,
    stressTest: {
      base:   { irr: 0.49, pd: 0.15 },
      stress: { irr: 0.29, pd: 0.30 },
      severe: { irr: 0.04, pd: 0.52 },
    },
    tags: ["EdTech", "K-12", "AI"],
    contact: {
      name: "Marcus Johnson",
      role: "Founder & CEO",
      email: "marcus@edusync.school",
      linkedin: "https://linkedin.com/in/marcusjohnson",
      website: "https://edusync.school",
      location: "Atlanta, GA",
      phone: "+1 (404) 556-2233",
    },
  },
  {
    id: "waterpulse",
    name: "WaterPulse",
    sector: "ClimaTech",
    stage: "Series A",
    logo: "WP",
    color: "from-blue-300 to-sky-600",
    description: "AI-powered water network monitoring system detecting leaks and contamination events in real time for municipal utilities.",
    expectedIRR: 0.40,
    pd12m: 0.08,
    fragilityScore: 19,
    revenueConcentration: 29,
    arrGrowth: 150,
    runway: 24,
    stressTest: {
      base:   { irr: 0.40, pd: 0.08 },
      stress: { irr: 0.26, pd: 0.18 },
      severe: { irr: 0.10, pd: 0.35 },
    },
    tags: ["ClimaTech", "Water", "Smart City"],
    contact: {
      name: "Ana Ferreira",
      role: "CEO & Founder",
      email: "ana@waterpulse.io",
      linkedin: "https://linkedin.com/in/anaferreira",
      website: "https://waterpulse.io",
      location: "Lisbon, Portugal",
      phone: "+351 21 234 5678",
    },
  },
  {
    id: "nomo-hr",
    name: "NomoHR",
    sector: "HRTech",
    stage: "Seed",
    logo: "NH",
    color: "from-orange-300 to-amber-600",
    description: "People analytics platform using NLP and engagement signals to predict and prevent employee churn 90 days in advance.",
    expectedIRR: 0.56,
    pd12m: 0.18,
    fragilityScore: 40,
    revenueConcentration: 52,
    arrGrowth: 320,
    runway: 11,
    stressTest: {
      base:   { irr: 0.56, pd: 0.18 },
      stress: { irr: 0.33, pd: 0.35 },
      severe: { irr: 0.03, pd: 0.57 },
    },
    tags: ["HRTech", "NLP", "B2B SaaS"],
    contact: {
      name: "Rachel Kim",
      role: "Co-Founder & CEO",
      email: "rachel@nomohr.com",
      linkedin: "https://linkedin.com/in/rachelkim",
      website: "https://nomohr.com",
      location: "Seoul, South Korea",
      phone: "+82 2 1234 5678",
    },
  },
  {
    id: "supply-ai",
    name: "SupplyAI",
    sector: "Supply Chain",
    stage: "Series A",
    logo: "SA",
    color: "from-stone-400 to-zinc-600",
    description: "Generative AI demand-forecasting engine reducing inventory overstock by 41% and stockouts by 37% for omnichannel retailers.",
    expectedIRR: 0.41,
    pd12m: 0.09,
    fragilityScore: 23,
    revenueConcentration: 33,
    arrGrowth: 158,
    runway: 19,
    stressTest: {
      base:   { irr: 0.41, pd: 0.09 },
      stress: { irr: 0.26, pd: 0.20 },
      severe: { irr: 0.09, pd: 0.37 },
    },
    tags: ["Supply Chain", "Generative AI", "Retail"],
    contact: {
      name: "David Okafor",
      role: "Founder & CEO",
      email: "david@supply.ai",
      linkedin: "https://linkedin.com/in/davidokafor",
      website: "https://supply.ai",
      location: "Amsterdam, Netherlands",
      phone: "+31 20 123 4567",
    },
  },
  {
    id: "lumena",
    name: "Lumena",
    sector: "MediaTech",
    stage: "Seed",
    logo: "LM",
    color: "from-fuchsia-400 to-violet-700",
    description: "AI dubbing and lip-sync studio enabling content creators to localise videos into 50 languages in under 10 minutes.",
    expectedIRR: 0.61,
    pd12m: 0.19,
    fragilityScore: 43,
    revenueConcentration: 54,
    arrGrowth: 390,
    runway: 12,
    stressTest: {
      base:   { irr: 0.61, pd: 0.19 },
      stress: { irr: 0.37, pd: 0.37 },
      severe: { irr: -0.03, pd: 0.61 },
    },
    tags: ["MediaTech", "Generative AI", "Creator Economy"],
    contact: {
      name: "Giulia Romano",
      role: "CEO & Co-Founder",
      email: "giulia@lumena.ai",
      linkedin: "https://linkedin.com/in/giuliaromano",
      website: "https://lumena.ai",
      location: "Milan, Italy",
      phone: "+39 02 1234 5678",
    },
  },
  {
    id: "deficore",
    name: "DeFiCore",
    sector: "Web3",
    stage: "Series A",
    logo: "DC",
    color: "from-purple-300 to-indigo-700",
    description: "Institutional-grade DeFi prime brokerage providing cross-chain liquidity aggregation and regulatory-compliant custody.",
    expectedIRR: 0.50,
    pd12m: 0.16,
    fragilityScore: 37,
    revenueConcentration: 45,
    arrGrowth: 200,
    runway: 15,
    stressTest: {
      base:   { irr: 0.50, pd: 0.16 },
      stress: { irr: 0.28, pd: 0.33 },
      severe: { irr: 0.02, pd: 0.56 },
    },
    tags: ["Web3", "DeFi", "Institutional"],
    contact: {
      name: "Andrei Popescu",
      role: "Founder & CTO",
      email: "andrei@deficore.finance",
      linkedin: "https://linkedin.com/in/andreipopescu",
      website: "https://deficore.finance",
      location: "Bucharest, Romania",
      phone: "+40 21 234 5678",
    },
  },
  {
    id: "skymesh",
    name: "SkyMesh",
    sector: "Telecom",
    stage: "Seed",
    logo: "SM",
    color: "from-cyan-300 to-teal-700",
    description: "Mesh-networking drone relay system providing emergency broadband to disaster-struck regions within 30 minutes of deployment.",
    expectedIRR: 0.69,
    pd12m: 0.24,
    fragilityScore: 52,
    revenueConcentration: 60,
    arrGrowth: 510,
    runway: 10,
    stressTest: {
      base:   { irr: 0.69, pd: 0.24 },
      stress: { irr: 0.41, pd: 0.44 },
      severe: { irr: -0.12, pd: 0.68 },
    },
    tags: ["Telecom", "Drones", "Emergency Tech"],
    contact: {
      name: "Olusegun Adeyemi",
      role: "CEO & Founder",
      email: "segun@skymesh.aero",
      linkedin: "https://linkedin.com/in/segun-adeyemi",
      website: "https://skymesh.aero",
      location: "Nairobi, Kenya",
      phone: "+254 20 123 4567",
    },
  },
];

export function computeRAR(startup) {
  return startup.expectedIRR * (1 - startup.pd12m);
}

export function rankStartups(startups, { minIRR, maxPD }) {
  return startups
    .filter((s) => s.expectedIRR >= minIRR && s.pd12m <= maxPD)
    .map((s) => ({ ...s, rar: computeRAR(s) }))
    .sort((a, b) => b.rar - a.rar);
}
